### ISSUE TITLE
Please Update the Name of Column From "addess" to "address"

### ISSUE THREAD

**Issue by gvssaimadhav** [kunaltyagi9/Employee-Management-System#1]
https://github.com/kunaltyagi9/Employee-Management-System/blob/fb8288b8497dd4c7f6b29bfb3cc3f3980c7b65f1/Employee-Management-System/src/Employeee/Print_Data.java#L28

- **Because of Spelling Mistake in the column name, only employee name and father name will get displayed!**, So I request you to update the typo

**Comment by kunaltyagi9** [comment]
@gvssaimadhav Could you please raise a MR/PR after fixing this issue, I will review and merge it

**Comment by gvssaimadhav** [comment]
> @gvssaimadhav Could you please raise a MR/PR after fixing this issue, I will review and merge it

Sure! doing it now

**Comment by kunaltyagi9** [comment]
@gvssaimadhav merged, thankyou
