### ISSUE TITLE
 Database of employee please 🙏

### ISSUE THREAD

**Issue by Anonymous10110** [kunaltyagi9/Employee-Management-System#3]
Can I get the database

**Comment by Anonymous10110** [comment]
Reply please 🥺

**Comment by sharmin19100038** [comment]
??

**Comment by sharmin19100038** [comment]
sry i don't notice your mail
I will send you tomorrow

**Comment by Anonymous10110** [comment]
Can I get plsss the database

**Comment by Anonymous10110** [comment]
Please 🙏

**Comment by kunaltyagi9** [comment]
check description of this video
https://www.youtube.com/watch?v=IeQ7t1P6_0A

**Comment by sharmin19100038** [comment]
I am extremely sorry vhiya

**Comment by sharmin19100038** [comment]
I am so busy my study that's why i was forget  to sending you  message.
So i am extremely  sry 🙂🙂
